export const types = {
  // Layout
  CHANGE_SIDEBAR_TYPE: '[LAYOUT] CHANGE_SIDEBAR_TYPE',
  // Auth
  AUTH_SET: '[AUTH] AUTH_SET',
  AUTH_UNSET: '[AUTH] AUTH_UNSET',
  AUTH_CHECKING: '[AUTH] AUTH_CHECKING',
  // Products
  PRODUCT_START: '[PRODUCT] PRODUCT_START',
  PRODUCT_SUCCESS: '[PRODUCT] PRODUCT_SUCCESS',
  PRODUCT_FAIL: '[PRODUCT] PRODUCT_FAIL',
  // TODO: User
};
